### ISSUE TITLE
Relationship betwen numLevels and Spark executors

### ISSUE THREAD

**Issue by clblalock** [ngmarchant/dblink#11]
Hi Neil, I have a few questions about the numLevels parameter and dblink's partitioning.

1. Does the numLevels control the mathematical partitions, the spark partitions, or both? We've gotten mixed answers to this question in the past. Our experience with dblink suggests that the numLevels parameter controls the spark partitions as we havent been able to  run a job with more partitions than those specified by numLevels. I think previously, Beka indicated that numLevels controls the mathematical partitions.

2. In order to get the ABSEmployee data, around 600k records, we had to change the config file that you provided to lower the numLevels from 6 to 4. While running with numLevels=6, we got a "bad partition" error, and we lowered the parameter on Beka's suggestion and everything ran correctly. With the 3 datasets that we've worked with, it seems that as the number of observations increase, the numLevels parameter needs to be reduced. Is this accurate? If so, it will pose a big challenge for processing datasets with millions of files because we won't be able farm out the extra work to more executors. 

3. If numLevels is not related to the dataset size, what are the data characterstics / factors that are going to determine how high the numLevels parameter can be set?

4. Are you or Beka working on a change that would let the mathematical and spark paritions be controlled separately so that the number of physical partitions can be increased? If I recall, Beka mentioned last month that you were working on an "indexing" issue, is that related to partitioning issue?

**Comment by ngmarchant** [comment]
Thanks for your questions.

>     1. Does the numLevels control the mathematical partitions, the spark partitions, or both? We've gotten mixed answers to this question in the past. Our experience with dblink suggests that the numLevels parameter controls the spark partitions as we havent been able to  run a job with more partitions than those specified by numLevels. I think previously, Beka indicated that numLevels controls the mathematical partitions.

The `numLevels` parameter is controlling the depth of the k-d tree used for partitioning the space. A larger value of `numLevels` will result in more partitions. There is a direct correspondence between the "mathematical" partitions and the Spark partitions. This must be so, as there are dependencies among model parameters _within_ a partition. This means the Gibbs updates for variables within a partition _cannot_ be distributed. 

>     2. In order to get the ABSEmployee data, around 600k records, we had to change the config file that you provided to lower the numLevels from 6 to 4. While running with numLevels=6, we got a "bad partition" error, and we lowered the parameter on Beka's suggestion and everything ran correctly. With the 3 datasets that we've worked with, it seems that as the number of observations increase, the numLevels parameter needs to be reduced. Is this accurate? If so, it will pose a big challenge for processing datasets with millions of files because we won't be able farm out the extra work to more executors.

I'm not sure what's happening here... I haven't seen a "bad partition error". We've been able to run dblink on ABSEmployee with `numLevels = 6`. Perhaps you could post a separate issue about this? With more details about the error.

>     3. If numLevels is not related to the dataset size, what are the data characterstics / factors that are going to determine how high the numLevels parameter can be set?

As mentioned above, `numLevels` is controlling the granularity of the partitioning of the entity space. This partitioning is introduced to make MCMC more scalable, however it can result in poorer mixing. If the entities are "well-separated" then `numLevels` can probably be increased with only a minor impact on convergence/mixing. 

Note: it's possible to improve on the k-d tree partitioner. You could write a custom partitioner which is tailored to the data you're working with.

>     4. Are you or Beka working on a change that would let the mathematical and spark paritions be controlled separately so that the number of physical partitions can be increased? If I recall, Beka mentioned last month that you were working on an "indexing" issue, is that related to partitioning issue?

Fundamentally, it's difficult to distribute the inference as the model parameters are densely connected.  This is why we introduced the partitions: by conditioning on the partitions, we can break some of the dependencies during inference (without resorting to an approximation). I can't see another way around this, unless you're willing to resort to approximations.

I'm not sure whether @resteorts has any ideas. And I'm not sure what the "indexing" issue is referring to.

**Comment by resteorts** [comment]
Thanks, Neil.

Yes, we chatted about these questions and I had similar answers awhile ago.





On Jan 17, 2020, at 3:23 AM, Neil Marchant <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for your questions.

1. Does the numLevels control the mathematical partitions, the spark partitions, or both? We've gotten mixed answers to this question in the past. Our experience with dblink suggests that the numLevels parameter controls the spark partitions as we havent been able to  run a job with more partitions than those specified by numLevels. I think previously, Beka indicated that numLevels controls the mathematical partitions.


The numLevels parameter is controlling the depth of the k-d tree used for partitioning the space. A larger value of numLevels will result in more partitions. There is a direct correspondence between the "mathematical" partitions and the Spark partitions. This must be so, as there are dependencies among model parameters within a partition. This means the Gibbs updates must be performed on a single executor.

2. In order to get the ABSEmployee data, around 600k records, we had to change the config file that you provided to lower the numLevels from 6 to 4. While running with numLevels=6, we got a "bad partition" error, and we lowered the parameter on Beka's suggestion and everything ran correctly. With the 3 datasets that we've worked with, it seems that as the number of observations increase, the numLevels parameter needs to be reduced. Is this accurate? If so, it will pose a big challenge for processing datasets with millions of files because we won't be able farm out the extra work to more executors.


I'm not sure what's happening here... I haven't seen a "bad partition error". We've been able to run dblink on ABSEmployee with numLevels = 6. Perhaps you could post a separate issue about this? With more details about the error.

3. If numLevels is not related to the dataset size, what are the data characterstics / factors that are going to determine how high the numLevels parameter can be set?


As mentioned above, numLevels is controlling the granularity of the partitioning of the entity space. This partitioning is introduced to make MCMC more scalable, however it can result in poorer mixing. If the entities are "well-separated" then numLevels can probably be increased with only a minor impact on convergence/mixing.

Note: it's possible to improve on the k-d tree partitioner. You could write a custom partitioner which is tailored to the data you're working with.

4. Are you or Beka working on a change that would let the mathematical and spark paritions be controlled separately so that the number of physical partitions can be increased? If I recall, Beka mentioned last month that you were working on an "indexing" issue, is that related to partitioning issue?


Fundamentally, it's difficult to distribute the inference as the model parameters are densely connected. This is why we introduced the partitions: by conditioning on the partitions, we can break some of the dependencies during inference (without resorting to an approximation). I can't see another way around this, unless you're willing to resort to approximations.

I'm not sure whether @resteorts<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_resteorts&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=k0Os9to_LJqcai_kiG1NjQaT5Y6v4DTxHPQOT9l3Kcw&m=eAuyUGxsaVAJ2Vd8CLHdwyqQEabqGoIXdv1ASTm0_As&s=NhRMvB6gUmxlr7dcWF-hO7qDdfz_UKD6JS9svi7tFgs&e=> has any ideas. And I'm not sure what the "indexing" issue is referring to.

**Comment by clblalock** [comment]
Hi Neil, thank you for the explanation. I think I'm following. Regarding the ABSEmployee file with numLevel=6, I misspoke about the "bad partition" error. I'll open a new issue related to that file.
